INPUT_IMG_SHAPE = (512, 512, 1)
OUTPUT_IMG_SHAPE = (224, 224, 12)
CROP_SIZE = (128, 128, 12)
CROP = False
BATCH_SIZE = 32
EPOCHS = 100
HASH_BUCKET_SIZE = 500
# https://www.quora.com/How-do-I-determine-the-number-of-dimensions-for-word-embedding
EMBEDDING_DIMS = int(HASH_BUCKET_SIZE ** 0.25) + 1
HIDDEN_UNITS = [10, 5]
CONCAT_HIDDEN_UNITS = [200, 50]
SHUFFLE_BUFFER_SIZE = 487_344  # we can now shuffle all data
TENSORBOARD_UPDATE_FREQUENCY = 500  # setting this too high will slow training!
# TENSORBOARD_UPDATE_FREQUENCY = 30
RANDOM_SPLIT_SEED = 55
TRAIN = True
# TRAIN = False
config = {
    "INPUT_IMG_SHAPE": INPUT_IMG_SHAPE,
    "OUTPUT_IMG_SHAPE": OUTPUT_IMG_SHAPE,
    "CROP_SIZE": CROP_SIZE,
    "CROP": CROP,
    "BATCH_SIZE": BATCH_SIZE,
    "EPOCHS": EPOCHS,
    "HASH_BUCKET_SIZE": HASH_BUCKET_SIZE,
    "EMBEDDING_DIMS": EMBEDDING_DIMS,
    "HIDDEN_UNITS": HIDDEN_UNITS,
    "CONCAT_HIDDEN_UNITS": CONCAT_HIDDEN_UNITS,
    "SHUFFLE_BUFFER_SIZE": SHUFFLE_BUFFER_SIZE,
    "TENSORBOARD_UPDATE_FREQUENCY": TENSORBOARD_UPDATE_FREQUENCY,
    "RANDOM_SPLIT_SEED": RANDOM_SPLIT_SEED,
    "TRAIN": TRAIN,
}